CREATE DATABASE smartq;
USE smartq;

CREATE TABLE tokens(id INT AUTO_INCREMENT PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE settings(id TINYINT PRIMARY KEY, current_token INT DEFAULT 0);
INSERT INTO settings VALUES(1,0);
